name: Generate Includes

on:
  push:
    branches:
      - master

jobs:
  generateIncludes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Run the script to generate cards.json
    - name: Generate cards.json
      run: node generators/generateCards.js

    # Configure Git
    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    # Check for changes
    - name: Check for changes
      run: git pull

    # Add, commit, and push changes
    - name: Commit and push cards.json
      run: |
        git add public/cards.json
        git commit -m "(CI) cards.json Generation" || echo "No changes to commit"
        git push
