name: Generate Screenshots

on:
  push:
    branches:
      - master

jobs:
  screenshots:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Fetch full history to ensure all commits are accessible

    # Install Puppeteer
    - name: Install Puppeteer
      run: npm install puppeteer

    # Run Puppeteer script to generate screenshots
    - name: Generate screenshots
      run: node generators/generateScreenshot.js

    # Commit screenshots
    - name: Commit screenshots
      uses: EndBug/add-and-commit@v9
      with:
        add: 'Art/**/icon.png'
        message: 'Add generated screenshots'
        author_name: 'GitHub Actions'
        author_email: 'actions@github.com'
