name: Generate Screenshots

on:
  push:
    branches:
      - master

jobs:
  screenshots:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Fetch full history to ensure all commits are accessible

    # Install Puppeteer
    - name: Install Puppeteer
      run: npm install puppeteer

    # Run Puppeteer script to generate screenshots
    - name: Generate screenshots
      run: node generators/generateScreenshot.js

      # Commit screenshots
    - name: Push Back Formatted Code
      run: |
        # configure git
        git config --global user.name "Matt Smith"
        git config --global user.email "mattcsmith@users.noreply.github.com"

        git add .
        git commit -m "(CI) Screenshot Generation"
        git push