name: Validate HTML and CSS

on:
  pull_request:
    branches:
      - master

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Validate HTML
    - name: Install HTMLHint
      run: npm install -g htmlhint

    - name: Run HTMLHint
      run: htmlhint "Art/**/*.html"

    # Validate CSS
    - name: Install Stylelint
      run: npm install -g stylelint stylelint-config-standard

    - name: Run Stylelint
      run: stylelint "Art/**/*.css"
